
################################################################################
# This program performs ANOVA repeated measures statistical tests for frequency analysis. 
# This compares impairment groups and for each grop individually
# Statistical results are published to output file created by sink()

# The exANOVA function in the ez package is used to perform statistical tests.
# This package and dependencies will need to be installed.
# To install run : install.package("ez")
################################################################################
# INSTRUCTIONS:
#     Change DIR, data, and the sink file before running in the terminal
#     To run in the terminal
#     $ R
#     Then run the script by executing the following
#     > source('freq-stats.r')
#     If running from console on windows computer, use setwd
#     for example - setwd('C:/Users/numur/Desktop/HapticMaster/FrequencyAnalysis')
################################################################################
# COMMENTS:
# There are two equivalent ways of performing a repeated measures ANOVA:
#   1. aov(Score~(SupportLevel*SL_setnum) + Error(Subject/(SupportLevel*SL_setnum)))
#   2. ezANOVA(data,dv=Score,wid=Subject,within = .(SupportLevel,SL_setnum),between = NULL, detailed = TRUE)
# The second also tests for sphericity, but sometimes gives errors if nothing is significant.
################################################################################

options(contrasts=c("contr.sum","contr.poly"))
remove(list = ls())
library(ez) # loads the ez package and dependencies

DIR = 'Z:' # for Milli: 'Z:' ; for Ola: '/media/ola/Elements/R01prelim/'
sink(paste(DIR,paste("freq","stats2.txt",sep="-"),sep="/"))

data = read.csv(paste(DIR,paste("freq","metrics.csv",sep="-"),sep="/"))
attach(data)
#################################################
cat("\n")
cat("################################################## ALL GROUPS################################### \n")
cat("##################################################FmagPeak############ \n")
mod.ez<-ezANOVA(data,FmagPeak,Subject,within = .(SupportLevel),between = Impairment, detailed = TRUE)
print(mod.ez)
cat("##################################################DiffPeak############ \n")
mod.ez<-ezANOVA(data,DiffPeak,Subject,within = .(SupportLevel,Task),between = Impairment, detailed = TRUE)
print(mod.ez)
cat("##################################################Ratio############ \n")
mod.ez<-ezANOVA(data,Ratio,Subject,within = .(SupportLevel,Task),between = Impairment, detailed = TRUE)
print(mod.ez)
# hi = anova(data, Ratio=~(SupportLevel*Task) + Error(Subject/(SupportLevel*Task)), X=~channel, idata=inDf, test="Spherical")
# # FmagPeakmodel<-aov(FmagPeak~(SupportLevel*Impairment) + Error(Subject/(SupportLevel)))
# # print(summary(FmagPeakmodel))
# # jpeg(paste(DIR,'FmagPeak.jpg',sep="/"))
# # boxplot(FmagPeak~SupportLevel*Impairment,main = paste("All groups"),xlab = "Limb Weight",ylab="FmagPeak",
# #       col=c('firebrick1','dodgerblue3')) # ,ylim=c(0,40)
# # dev.off()
cat("##################################################FxPeak############ \n")
mod.ez<-ezANOVA(data,FxPeak,Subject,within = .(SupportLevel,Task),between = Impairment, detailed = TRUE)
print(mod.ez)
jpeg(paste(DIR,'FxPeak.jpg',sep="/"))
boxplot(FxPeak~SupportLevel*Impairment,main = paste("All groups"),xlab = "Limb Weight",ylab="FmagPeak",
      col=c('firebrick1','dodgerblue3')) # ,ylim=c(0,40)
dev.off()
cat("##################################################FyPeak############ \n")
mod.ez<-ezANOVA(data,FyPeak,Subject,within = .(SupportLevel,Task),between = Impairment, detailed = TRUE)
print(mod.ez)
# cat("##################################################PxPeak############ \n")
# mod.ez<-ezANOVA(data,PxPeak,Subject,within = .(SupportLevel,Task),between = Impairment, detailed = TRUE)
# print(mod.ez)
# cat("##################################################PyPeak############ \n")
# mod.ez<-ezANOVA(data,PyPeak,Subject,within = .(SupportLevel,Task),between = Impairment, detailed = TRUE)
# print(mod.ez)
cat("##################################################RatioFx############ \n")
mod.ez<-ezANOVA(data,RatioFx,Subject,within = .(SupportLevel,Task),between = Impairment, detailed = TRUE)
print(mod.ez)
jpeg(paste(DIR,'RatioFx.jpg',sep="/"))
boxplot(RatioFx~SupportLevel*Impairment,main = paste("All groups"),xlab = "Limb Weight",ylab="FmagPeak",
        col=c('firebrick1','dodgerblue3')) # ,ylim=c(0,40)
dev.off()
cat("##################################################RatioFy############ \n")
mod.ez<-ezANOVA(data,RatioFy,Subject,within = .(SupportLevel,Task),between = Impairment, detailed = TRUE)
print(mod.ez)
jpeg(paste(DIR,'RatioFy.jpg',sep="/"))
boxplot(RatioFy~SupportLevel*Impairment,main = paste("All groups"),xlab = "Limb Weight",ylab="FmagPeak",
        col=c('firebrick1','dodgerblue3')) # ,ylim=c(0,40)
dev.off()
cat("##################################################FxHigh############ \n")
mod.ez<-ezANOVA(data,FxHigh,Subject,within = .(SupportLevel,Task),between = Impairment, detailed = TRUE)
print(mod.ez)
detach(data)


data_stroke = read.csv(paste(DIR,paste("freq","metrics","stroke.csv",sep="-"),sep="/"))
attach(data_stroke)
cat("\n")
cat("################################################## STROKE ################################### \n")
cat("##################################################FmagPeak############ \n")
mod.ez<-ezANOVA(data_stroke,FmagPeak,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
print(mod.ez)
# FmagPeakmodel<-aov(FmagPeak~(SupportLevel*Task) + Error(Subject/(SupportLevel*Task)))
# print(summary(FmagPeakmodel))
cat("##################################################DiffPeak############ \n")
mod.ez<-ezANOVA(data_stroke,DiffPeak,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
print(mod.ez)
cat("##################################################Ratio############ \n")
mod.ez<-ezANOVA(data_stroke,Ratio,Subject,within = .(SupportLevel),between = NULL, detailed = TRUE)
print(mod.ez)
mod.ez<-ezANOVA(data_stroke,Ratio,Subject,within = .(Task),between = NULL, detailed = TRUE)
print(mod.ez)
model<-aov(Ratio~(SupportLevel*Task) + Error(Subject/(SupportLevel*Task)))
print(summary(model))
cat("##################################################FxPeak############ \n")
mod.ez<-ezANOVA(data_stroke,FxPeak,Subject,within = .(SupportLevel),between = NULL, detailed = TRUE)
print(mod.ez)
mod.ez<-ezANOVA(data_stroke,FxPeak,Subject,within = .(Task),between = NULL, detailed = TRUE)
print(mod.ez)
model<-aov(FxPeak~(SupportLevel*Task) + Error(Subject/(SupportLevel*Task)))
print(summary(model))
cat("##################################################FyPeak############ \n")
mod.ez<-ezANOVA(data_stroke,FyPeak,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
print(mod.ez)
# cat("##################################################PxPeak############ \n")
# mod.ez<-ezANOVA(data_stroke,PxPeak,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
# print(mod.ez)
# cat("##################################################PyPeak############ \n")
# PyPeakmodel<-aov(PyPeak~(SupportLevel*Task) + Error(Subject/(SupportLevel*Task)))
# print(summary(PyPeakmodel))
# # mod.ez<-ezANOVA(data_stroke,PyPeak,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
# # print(mod.ez)
cat("##################################################RatioFx############ \n")
mod.ez<-ezANOVA(data_stroke,RatioFx,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
print(mod.ez)
cat("##################################################RatioFy############ \n")
mod.ez<-ezANOVA(data_stroke,RatioFy,Subject,within = .(SupportLevel),between = NULL, detailed = TRUE)
print(mod.ez)
mod.ez<-ezANOVA(data_stroke,RatioFy,Subject,within = .(Task),between = NULL, detailed = TRUE)
print(mod.ez)
model<-aov(RatioFy~(SupportLevel*Task) + Error(Subject/(SupportLevel*Task)))
print(summary(model))
# mod.ez<-ezANOVA(data_stroke,RatioFy,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
# print(mod.ez)
cat("##################################################FxHigh############ \n")
# mod.ez<-ezANOVA(data_stroke,FxHigh,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
# print(mod.ez)
mod.ez<-ezANOVA(data_stroke,FxHigh,Subject,within = .(SupportLevel),between = NULL, detailed = TRUE)
print(mod.ez)
mod.ez<-ezANOVA(data_stroke,FxHigh,Subject,within = .(Task),between = NULL, detailed = TRUE)
print(mod.ez)
model<-aov(FxHigh~(SupportLevel*Task) + Error(Subject/(SupportLevel*Task)))
print(summary(model))
l1 = data_stroke$FxHigh[data_stroke$SupportLevel=="0%Max"]
l2 = data_stroke$FxHigh[data_stroke$SupportLevel=="20%Max"]
l3 = data_stroke$FxHigh[data_stroke$SupportLevel=="50%Max"]
results <- t.test(l1, l2, mu = 0, paired = FALSE)
if (results$p.value<0.1){
  print(results$data.name)
  print(results$p.value/2)
}
results <- t.test(l2, l3, mu = 0, paired = FALSE)
if (results$p.value<0.1){
  print(results$data.name)
  print(results$p.value/2)
}
results <- t.test(l1, l3, mu = 0, paired = FALSE)
if (results$p.value<0.1){
  print(results$data.name)
  print(results$p.value/2)
}
detach(data_stroke)

data_controls = read.csv(paste(DIR,paste("freq","metrics","controls.csv",sep="-"),sep="/"))
attach(data_controls)
cat("\n")
cat("################################################## CONTROLS ################################### \n")
cat("##################################################FmagPeak############ \n")
mod.ez<-ezANOVA(data_controls,FmagPeak,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
print(mod.ez)
cat("##################################################DiffPeak############ \n")
mod.ez<-ezANOVA(data_controls,DiffPeak,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
print(mod.ez)
cat("##################################################Ratio############ \n")
# mod.ez<-ezANOVA(data_controls,Ratio,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
# print(mod.ez)
cat("##################################################FxPeak############ \n")
# mod.ez<-ezANOVA(data_controls,FxPeak,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
# print(mod.ez)
mod.ez<-ezANOVA(data_controls,FxPeak,Subject,within = .(SupportLevel),between = NULL, detailed = TRUE)
print(mod.ez)
mod.ez<-ezANOVA(data_controls,FxPeak,Subject,within = .(Task),between = NULL, detailed = TRUE)
print(mod.ez)
model<-aov(FxPeak~(SupportLevel*Task) + Error(Subject/(SupportLevel*Task)))
print(summary(model))
cat("##################################################FyPeak############ \n")
mod.ez<-ezANOVA(data_controls,FyPeak,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
print(mod.ez)
# FyPeakmodel<-aov(FyPeak~(SupportLevel*Task) + Error(Subject/(SupportLevel*Task)))
# print(summary(FyPeakmodel))
# cat("##################################################PxPeak############ \n")
# mod.ez<-ezANOVA(data_controls,PxPeak,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
# print(mod.ez)
# cat("##################################################PyPeak############ \n")
# mod.ez<-ezANOVA(data_controls,PyPeak,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
# print(mod.ez)
cat("##################################################RatioFx############ \n")
mod.ez<-ezANOVA(data_controls,RatioFx,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
print(mod.ez)
cat("##################################################RatioFy############ \n")
mod.ez<-ezANOVA(data_controls,RatioFy,Subject,within = .(SupportLevel),between = NULL, detailed = TRUE)
print(mod.ez)
mod.ez<-ezANOVA(data_controls,RatioFy,Subject,within = .(Task),between = NULL, detailed = TRUE)
print(mod.ez)
model<-aov(RatioFy~(SupportLevel*Task) + Error(Subject/(SupportLevel*Task)))
print(summary(model))
cat("##################################################FxHigh############ \n")
mod.ez<-ezANOVA(data_controls,RatioFy,Subject,within = .(SupportLevel),between = NULL, detailed = TRUE)
print(mod.ez)
mod.ez<-ezANOVA(data_controls,RatioFy,Subject,within = .(Task),between = NULL, detailed = TRUE)
print(mod.ez)
model<-aov(RatioFy~(SupportLevel*Task) + Error(Subject/(SupportLevel*Task)))
print(summary(model))
mod.ez<-ezANOVA(data_controls,FxHigh,Subject,within = .(SupportLevel,Task),between = NULL, detailed = TRUE)
print(mod.ez)
detach(data_controls)
